# Setup
title:        KURIAN BENOY
tagline:      An Enthusiast Programmer, Open source Enthusiast , Photographer
baseurl:      ""
paginate:     5
locale:       "en"

# About/contact
author:
  name:       Kurian Benoy
  url:        https://kurianbenoy.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
